# Generated by Django 3.1 on 2020-08-22 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='History',
        ),
    ]
