# Generated by Django 3.1 on 2020-08-21 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='directors',
            field=models.TextField(default='Default'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='screen_play',
            field=models.TextField(default='Default'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_genre',
            field=models.ManyToManyField(to='cinema_core.Genre'),
        ),
    ]
